"""news tables trainitg + types_activities

Revision ID: 1d8df1413f23
Revises: 88c39b8ba58c
Create Date: 2026-03-29 21:45:42.585284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8df1413f23'
down_revision: Union[str, Sequence[str], None] = '88c39b8ba58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('type_activ_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('type_activ_id')
    )
    op.create_table('completed_training',
    sa.Column('active_training_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_activ_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_training', sa.Text(), nullable=True),
    sa.Column('kilocalories', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('active_training_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed_training')
    op.drop_table('activity_types')
    # ### end Alembic commands ###
