"""add gps_track to completed_training and drop training_gps_points

Revision ID: 4189dbb5a574
Revises: 589e9f805a94
Create Date: 2026-04-08 20:29:23.267008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4189dbb5a574'
down_revision: Union[str, Sequence[str], None] = '589e9f805a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_training', sa.Column('gps_track', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    #op.create_index('idx_completed_training_gps_track', 'completed_training', ['gps_track'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_completed_training_gps_track', table_name='completed_training', postgresql_using='gist')
    op.drop_column('completed_training', 'gps_track')
    # ### end Alembic commands ###
