"""gps postgres

Revision ID: 589e9f805a94
Revises: 9097c4b72eff
Create Date: 2026-04-05 22:28:28.243166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589e9f805a94'
down_revision: Union[str, Sequence[str], None] = '9097c4b72eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_gps_points',
    sa.Column('gps_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('training_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['completed_training.training_id'], ),
    sa.PrimaryKeyConstraint('gps_id')
    )
    op.create_index(op.f('ix_training_gps_points_training_id'), 'training_gps_points', ['training_id'], unique=False)
    op.drop_constraint(op.f('club_organizer_user_id_fkey'), 'club_organizer', type_='foreignkey')
    op.create_foreign_key(None, 'club_organizer', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(op.f('completed_training_user_id_fkey'), 'completed_training', type_='foreignkey')
    op.create_foreign_key(None, 'completed_training', 'users', ['user_id'], ['user_id'])
    op.alter_column('email_verifications', 'code',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=6),
               existing_nullable=False)
    op.drop_constraint(op.f('email_verifications_user_id_fkey'), 'email_verifications', type_='foreignkey')
    op.create_foreign_key(None, 'email_verifications', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(op.f('trainers_user_id_fkey'), 'trainers', type_='foreignkey')
    op.create_foreign_key(None, 'trainers', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(op.f('user_and_goal_user_id_fkey'), 'user_and_goal', type_='foreignkey')
    op.create_foreign_key(None, 'user_and_goal', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(op.f('user_and_role_user_id_fkey'), 'user_and_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_and_role', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_and_role', type_='foreignkey')
    op.create_foreign_key(op.f('user_and_role_user_id_fkey'), 'user_and_role', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_and_goal', type_='foreignkey')
    op.create_foreign_key(op.f('user_and_goal_user_id_fkey'), 'user_and_goal', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'trainers', type_='foreignkey')
    op.create_foreign_key(op.f('trainers_user_id_fkey'), 'trainers', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'email_verifications', type_='foreignkey')
    op.create_foreign_key(op.f('email_verifications_user_id_fkey'), 'email_verifications', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.alter_column('email_verifications', 'code',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_constraint(None, 'completed_training', type_='foreignkey')
    op.create_foreign_key(op.f('completed_training_user_id_fkey'), 'completed_training', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'club_organizer', type_='foreignkey')
    op.create_foreign_key(op.f('club_organizer_user_id_fkey'), 'club_organizer', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_training_gps_points_training_id'), table_name='training_gps_points')
    op.drop_table('training_gps_points')
    # ### end Alembic commands ###
