"""add MET activity tables

Revision ID: dd9e5d903073
Revises: a6cf1b1881f7
Create Date: 2026-04-13 19:45:05.854472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'dd9e5d903073'
down_revision: Union[str, Sequence[str], None] = 'a6cf1b1881f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_met_info',
    sa.Column('met_info_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_activ_id', sa.Integer(), nullable=False),
    sa.Column('base_met', sa.Float(), nullable=False),
    sa.Column('uses_speed_zones', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['type_activ_id'], ['activity_types.type_activ_id'], ),
    sa.PrimaryKeyConstraint('met_info_id'),
    sa.UniqueConstraint('type_activ_id')
    )
    op.create_table('activity_met_zones',
    sa.Column('met_zone_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_met_id', sa.Integer(), nullable=False),
    sa.Column('speed_min', sa.Float(), nullable=True),
    sa.Column('speed_max', sa.Float(), nullable=True),
    sa.Column('met_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['activity_met_id'], ['activity_met_info.met_info_id'], ),
    sa.PrimaryKeyConstraint('met_zone_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_met_zones')
    op.drop_table('activity_met_info')
    # ### end Alembic commands ###
