"""elevation gain

Revision ID: f6465c2026cc
Revises: fdcc911f048d
Create Date: 2026-05-17 15:13:12.639845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6465c2026cc'
down_revision: Union[str, Sequence[str], None] = 'fdcc911f048d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_training', sa.Column('elevation_gain', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('completed_training', 'elevation_gain')
    # ### end Alembic commands ###
